version: '3.9'
 
services:
  nxtrans-ai-prod:
    image: nxtrans-ai-prod
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'nxtrans-ai-prod'
    logging:
      options:
        max-size: "5m"
        max-file: "3"
    ports:
      - ${DOCKER_PORT}:4000
    env_file:
      - .env
    entrypoint: /bin/sh
    restart: always
    command:
      - ./scripts/start_server.sh
    networks:
      - nxtrans-ai-prod
networks:
  nxtrans-ai-prod:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  17.103.0.0/16
